### ISSUE TITLE
Item - Item Collaborative Filtering Testing

### ISSUE THREAD

**Issue by Kattarishabh** [jayeshjakkani/SE21-project#3]

**Comment by Kattarishabh** [comment]
Add Final Item- Item CF code

**Comment by jayeshjakkani** [comment]
Add provisional item-item collaborative testing code

**Comment by jayeshjakkani** [comment]
Update the csv file paths for proper execution

**Comment by jayeshjakkani** [comment]
Add comments for better code readability

**Comment by jayeshjakkani** [comment]
Issue closed
